# Generated by Django 5.2.6 on 2025-09-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividaddifusion',
            old_name='Proyecto',
            new_name='proyecto',
        ),
    ]
