# Generated by Django 5.2.6 on 2025-09-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_actividad_encargado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadbase',
            name='n_act',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
