# Generated by Django 5.2.6 on 2025-09-16 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_rename_proyecto_actividaddifusion_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(db_index=True)),
                ('enviado', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='proyectos.actividadbase')),
            ],
        ),
    ]
